# Generated by Django 3.2.16 on 2022-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesHrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('jatah_cuti', models.CharField(max_length=120, null=True)),
                ('sisa_cuti', models.CharField(max_length=24, null=True)),
                ('tanggal_cuti', models.DateField(null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
