# Generated by Django 3.2.16 on 2022-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshrd',
            name='tanggal_cuti',
            field=models.DateField(blank=True, null=True),
        ),
    ]
