# Generated by Django 3.2.16 on 2022-12-23 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_noteshrd_tanggal_cuti'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutiHr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisa_cuti', models.CharField(max_length=24, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='noteshrd',
            name='data_cuti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.cutihr'),
        ),
    ]
