# Generated by Django 3.2.16 on 2023-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20230208_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshrd',
            name='type_notes',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
