# Generated by Django 3.2.16 on 2023-02-08 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20230208_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshrd',
            name='date_note',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
