# Generated by Django 3.2.16 on 2023-02-08 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20230208_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshrd',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='noteshrd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
