# Generated by Django 3.2.16 on 2023-02-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_remove_noteshrd_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshrd',
            name='bulan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteshrd',
            name='hari',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteshrd',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
