# Generated by Django 3.2.16 on 2023-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_remove_noteshrd_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshrd',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteshrd',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noteshrd',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
