# Generated by Django 3.2.16 on 2023-02-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20230216_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteshrd',
            name='day',
        ),
        migrations.RemoveField(
            model_name='noteshrd',
            name='month',
        ),
        migrations.RemoveField(
            model_name='noteshrd',
            name='years',
        ),
    ]
