# Generated by Django 3.2.16 on 2023-02-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20230216_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteshrd',
            old_name='day',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='noteshrd',
            old_name='month',
            new_name='months',
        ),
    ]
