# Generated by Django 3.2.16 on 2023-02-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20230216_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshrd',
            name='notes_optional',
            field=models.TextField(max_length=230, null=True),
        ),
    ]
