# Generated by Django 3.2.16 on 2023-02-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_alter_noteshrd_notes_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteshrd',
            old_name='day_notes',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='noteshrd',
            old_name='month_notes',
            new_name='months',
        ),
        migrations.RenameField(
            model_name='noteshrd',
            old_name='year_notes',
            new_name='years',
        ),
    ]
