version: "2"
services:
  nginx:
    build: ./config/nginx
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn backendPeti.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./backendPeti:/backendPeti
      - ./.env:/backendPeti/backendPeti/.env
    environment:
      - DJANGO_SETTINGS_MODULE=backendPeti.settings_prod
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: