# Generated by Django 3.2.16 on 2023-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDash', '0004_alter_dashboardhrd_total_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendardashhrd',
            old_name='title_days',
            new_name='title_day',
        ),
        migrations.AddField(
            model_name='calendardashhrd',
            name='type_day',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_days',
            field=models.IntegerField(null=True),
        ),
    ]
