# Generated by Django 3.2.16 on 2023-01-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardashhrd',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendardashhrd',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendardashhrd',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='hour_perday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_days',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_hour',
            field=models.IntegerField(null=True),
        ),
    ]
