# Generated by Django 3.2.16 on 2023-01-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDash', '0002_auto_20230118_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardhrd',
            name='hour_perday',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_days',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_employee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboardhrd',
            name='total_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
