# Generated by Django 3.2.16 on 2023-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDash', '0005_auto_20230119_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardashhrd',
            name='day_of',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
