# Generated by Django 3.2.16 on 2023-02-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDash', '0006_calendardashhrd_day_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardashhrd',
            name='day_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='calendardashhrd',
            name='day_opt',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
