# Generated by Django 3.2.16 on 2023-02-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarDash', '0007_auto_20230216_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendardashhrd',
            old_name='day_opt',
            new_name='day_opti',
        ),
    ]
