# Generated by Django 3.2.15 on 2023-09-27 13:12

import backendPeti.helper.file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/bank/'))),
            ],
        ),
    ]
