# Generated by Django 3.2.16 on 2023-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20230110_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
