# Generated by Django 3.2.16 on 2023-01-15 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20230115_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='true', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
