# Generated by Django 3.2.16 on 2023-01-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_useractive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActive',
        ),
    ]
