# Generated by Django 3.2.16 on 2023-01-16 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_useractive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractive',
            name='userActived',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimas', to=settings.AUTH_USER_MODEL),
        ),
    ]
