# Generated by Django 3.2.16 on 2023-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_delete_useractive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
