# Generated by Django 3.2.16 on 2023-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_user_employee_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
