# Generated by Django 3.2.16 on 2023-01-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_user_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
