# Generated by Django 3.2.16 on 2023-01-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
