# Generated by Django 3.2.16 on 2023-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_alter_user_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sisa_cuti',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
