# Generated by Django 3.2.16 on 2023-02-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_alter_user_sisa_cuti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
