# Generated by Django 3.2.16 on 2023-02-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_auto_20230215_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
