# Generated by Django 3.2.15 on 2023-06-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_user_contract_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
