# Generated by Django 3.2.15 on 2023-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
