# Generated by Django 3.2.15 on 2023-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_employee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
