# Generated by Django 3.2.15 on 2023-09-27 13:12

import backendPeti.helper.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('userapp', '0033_usernotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('berkas', models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/sertifikat/'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='alamat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/foto/')),
        ),
        migrations.AddField(
            model_name='user',
            name='no_hp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_kawin',
            field=models.CharField(blank=True, default='belum menikah', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='UserNpwp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(blank=True, max_length=255, null=True)),
                ('berkas', models.FileField(blank=True, null=True, upload_to='user/npwp/')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserKTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(blank=True, max_length=255, null=True)),
                ('berkas', models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/ktp/'))),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContract',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('contract_time', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_level', models.CharField(blank=True, default='SMA/SMK', max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/certificate/'))),
                ('transkrip', models.ImageField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/certificate/transkrip/'))),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBpjs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(blank=True, max_length=255, null=True)),
                ('berkas', models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/bpjs/'))),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomor', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bank')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv', models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/cv/'))),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sertifikat', models.ManyToManyField(to='userapp.Certificate')),
            ],
        ),
    ]
