# Generated by Django 3.2.15 on 2023-09-27 14:52

import backendPeti.helper.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_auto_20230927_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBerkas',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.CharField(blank=True, max_length=255, null=True)),
                ('berkas_ktp', models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/ktp/'))),
                ('no_npwp', models.CharField(blank=True, max_length=255, null=True)),
                ('berkas_npwp', models.FileField(blank=True, null=True, upload_to='user/npwp/')),
                ('no_bpjs', models.CharField(blank=True, max_length=255, null=True)),
                ('berkas_bpjs', models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('user/bpjs/'))),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userktp',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='usernpwp',
            name='employee',
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='study_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserBpjs',
        ),
        migrations.DeleteModel(
            name='UserKTP',
        ),
        migrations.DeleteModel(
            name='UserNpwp',
        ),
    ]
