# Generated by Django 3.2.15 on 2023-09-29 04:42

import backendPeti.helper.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0035_auto_20230927_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='berkas',
            field=models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('sertifikat/')),
        ),
        migrations.AlterField(
            model_name='useradditionaldata',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('cv/')),
        ),
        migrations.AlterField(
            model_name='userberkas',
            name='berkas_bpjs',
            field=models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('bpjs/')),
        ),
        migrations.AlterField(
            model_name='userberkas',
            name='berkas_ktp',
            field=models.FileField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('ktp/')),
        ),
        migrations.AlterField(
            model_name='userberkas',
            name='berkas_npwp',
            field=models.FileField(blank=True, null=True, upload_to='npwp/'),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('certificate/')),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='transkrip',
            field=models.ImageField(blank=True, null=True, upload_to=backendPeti.helper.file.RandomFileName('certificate/transkrip/')),
        ),
    ]
