# Generated by Django 3.2.15 on 2023-11-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_auto_20230929_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionaldata',
            name='sertifikat',
            field=models.ManyToManyField(blank=True, null=True, to='userapp.Certificate'),
        ),
    ]
