# Generated by Django 3.2.16 on 2023-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0002_alter_attendanceemployee_working_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='employee_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='end_from',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='start_from',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='working_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
