# Generated by Django 3.2.16 on 2023-01-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0003_auto_20230116_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemployee',
            name='working_hour',
            field=models.IntegerField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='end_from',
            field=models.IntegerField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='start_from',
            field=models.IntegerField(blank=True, max_length=120, null=True),
        ),
    ]
