# Generated by Django 3.2.16 on 2023-01-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0004_auto_20230116_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='end_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='start_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='working_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
