# Generated by Django 3.2.16 on 2023-01-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0005_auto_20230116_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='employee_name',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='end_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='start_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='working_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='working_hour',
            field=models.IntegerField(null=True),
        ),
    ]
