# Generated by Django 3.2.16 on 2023-01-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0006_auto_20230117_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='working_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
