# Generated by Django 3.2.16 on 2023-01-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0007_alter_attendanceemployee_working_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageAttendanceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('total_working_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceemployee',
            name='months',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='attendanceemployee',
            name='years',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
