# Generated by Django 3.2.16 on 2023-01-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0008_auto_20230118_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='months',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='years',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
