# Generated by Django 3.2.16 on 2023-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0009_auto_20230118_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemployee',
            name='working_hour_detail',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
