# Generated by Django 3.2.16 on 2023-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0010_attendanceemployee_working_hour_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentageattendanceemployee',
            name='percentage',
            field=models.CharField(blank=True, max_length=245, null=True),
        ),
    ]
