# Generated by Django 3.2.16 on 2023-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0011_alter_percentageattendanceemployee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentageattendanceemployee',
            name='name_label',
            field=models.CharField(max_length=245, null=True),
        ),
    ]
