# Generated by Django 3.2.16 on 2023-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0014_auto_20230119_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemployee',
            name='lembur_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendanceemployee',
            name='lembur_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceemployee',
            name='lembur_start',
            field=models.IntegerField(null=True),
        ),
    ]
