# Generated by Django 3.2.16 on 2023-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0015_auto_20230119_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='end_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='lembur_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='lembur_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='start_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='working_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
