# Generated by Django 3.2.16 on 2023-01-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0016_auto_20230119_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemployee',
            name='working_hour_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
