# Generated by Django 3.2.16 on 2023-01-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0017_attendanceemployee_working_hour_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='lembur_hour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
