# Generated by Django 3.2.16 on 2023-01-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0018_alter_attendanceemployee_lembur_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='lembur_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
