# Generated by Django 3.2.16 on 2023-02-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0020_auto_20230120_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemployee',
            name='days',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
