# Generated by Django 3.2.16 on 2023-02-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0021_attendanceemployee_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceemployee',
            name='ket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
