# Generated by Django 3.2.16 on 2023-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceEmployee', '0022_attendanceemployee_ket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceemployee',
            name='days',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceemployee',
            name='ket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
