# Generated by Django 3.2.16 on 2022-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=120, null=True)),
                ('permission_type', models.CharField(max_length=24, null=True)),
                ('reason', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('permission_pil', models.CharField(blank=True, max_length=24, null=True)),
                ('reason_rejected', models.TextField(blank=True, null=True)),
                ('suspended_start', models.DateField(blank=True, null=True)),
                ('suspended_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
