# Generated by Django 3.2.16 on 2023-01-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0004_petitionscalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petitionscalendar',
            old_name='employee_name',
            new_name='title',
        ),
    ]
