# Generated by Django 3.2.16 on 2023-01-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0005_rename_employee_name_petitionscalendar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionscalendar',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='petitionscalendar',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
