# Generated by Django 3.2.16 on 2023-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0006_auto_20230108_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionscalendar',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='petitionscalendar',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
