# Generated by Django 3.2.16 on 2023-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0007_auto_20230108_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionscalendar',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='petitionscalendar',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
