# Generated by Django 3.2.16 on 2023-01-20 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0009_petitions_conditional_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='petitions',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
