# Generated by Django 3.2.16 on 2023-01-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0011_alter_petitions_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
