# Generated by Django 3.2.16 on 2023-01-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0012_alter_petitions_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitions',
            name='end_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitions',
            name='from_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petitions',
            name='lembur_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitions',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitions',
            name='jumlah_hari',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='petitions',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petitions',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
