# Generated by Django 3.2.16 on 2023-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0013_auto_20230120_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitions',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
