# Generated by Django 3.2.16 on 2023-01-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0014_alter_petitions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
