# Generated by Django 3.2.16 on 2023-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0016_alter_petitions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitions',
            name='jumlah_hari',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
