# Generated by Django 3.2.16 on 2023-04-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuanEmp', '0017_alter_petitions_jumlah_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionscalendar',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
