# Generated by Django 3.2.16 on 2022-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fistApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuans',
            name='division',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='employee_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='permission_pil',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='permission_type',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='reason_rejected',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pengajuans',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
