# Generated by Django 3.2.16 on 2022-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fistApp', '0003_auto_20221215_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuans',
            name='permission_pil',
            field=models.CharField(default=' ', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='pengajuans',
            name='reason_rejected',
            field=models.TextField(default=' ', null=True),
        ),
    ]
