# Generated by Django 3.2.16 on 2022-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fistApp', '0005_auto_20221215_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuans',
            name='permission_pil',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
