# Generated by Django 3.2.16 on 2023-03-01 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_date', models.DateField()),
                ('start_from', models.IntegerField(blank=True, null=True)),
                ('end_from', models.IntegerField(blank=True, null=True)),
                ('lembur_start', models.IntegerField(blank=True, null=True)),
                ('lembur_end', models.IntegerField(blank=True, null=True)),
                ('working_hour', models.IntegerField(blank=True, null=True)),
                ('lembur_hour', models.IntegerField(blank=True, null=True)),
                ('working_hour_total', models.IntegerField(blank=True, null=True)),
                ('working_hour_detail', models.FloatField(blank=True, null=True)),
                ('lembur_hour_detail', models.FloatField(blank=True, null=True)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=220, null=True)),
                ('ket', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
