# Generated by Django 3.2.16 on 2023-03-26 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenceEmployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenceemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_hours', to=settings.AUTH_USER_MODEL),
        ),
    ]
