# Generated by Django 3.2.15 on 2023-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenceEmployee', '0002_alter_presenceemployee_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenceemployee',
            name='is_lock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
