# Generated by Django 3.2.16 on 2022-12-23 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20221223_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jatah_cuti', models.CharField(max_length=120, null=True)),
                ('sisa_cuti', models.CharField(max_length=24, null=True)),
                ('tanggal_cuti', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('catatan', models.CharField(max_length=300, null=True)),
                ('employee_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
