# Generated by Django 3.2.16 on 2023-02-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_noteshrd_notes_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteshrd',
            name='notes_optional',
            field=models.TextField(blank=True, default='optional', max_length=230, null=True),
        ),
    ]
