# Generated by Django 3.2.16 on 2023-03-09 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarCutiSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=120, null=True)),
                ('permission_type', models.CharField(max_length=24, null=True)),
                ('reason', models.TextField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=120, null=True)),
                ('permission_type', models.CharField(max_length=24, null=True)),
                ('reason', models.TextField(null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('jumlah_hari', models.IntegerField(blank=True, null=True)),
                ('from_hour', models.IntegerField(blank=True, null=True)),
                ('end_hour', models.IntegerField(blank=True, null=True)),
                ('lembur_hour', models.IntegerField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('permission_pil', models.CharField(blank=True, max_length=24, null=True)),
                ('reason_rejected', models.TextField(blank=True, null=True)),
                ('conditional_reasons', models.TextField(blank=True, null=True)),
                ('suspended_start', models.DateField(blank=True, null=True)),
                ('suspended_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
