# Generated by Django 3.2.16 on 2023-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submisssion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='division',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='employee_name',
        ),
    ]
