# Generated by Django 3.2.16 on 2023-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submisssion', '0002_auto_20230315_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status_submission',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
