# Generated by Django 3.2.16 on 2023-03-16 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submisssion', '0003_submission_status_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarcutisubmission',
            name='division',
        ),
        migrations.AddField(
            model_name='calendarcutisubmission',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarcutisubmission',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
