# Generated by Django 3.2.16 on 2023-04-03 06:52

from django.db import migrations, models
import uuid

def convert_to_uuid(apps, schema_editor):
    Submission = apps.get_model('submisssion', 'Submission')
    for submission in Submission.objects.all():
        submission.uuid_id = uuid.UUID(int=submission.id)
        submission.save()

class Migration(migrations.Migration):

    dependencies = [
        ('submisssion', '0004_auto_20230316_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='uuid_id',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(convert_to_uuid),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='id',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='uuid_id',
            new_name='id',
        ),
    ]
