# Generated by Django 3.2.15 on 2023-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submisssion', '0006_rename_uuid_id_submission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarcutisubmission',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
